name: ci

on:
  push:
    branches:
      - v4-pika

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 14
          check-latest: true

      - name: Cache Nuxt
        id: nuxt-cache-build
        uses: actions/cache@v2
        with:
          path: |
            .nuxt
            node_modules
          key: ${{ runner.os }}-nuxt-logotip4ik-portfolio-v4-build-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-nuxt-logotip4ik-portfolio-v4-build-

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build
