name: ci

on:
  push:
    branches:
      - v4-pika

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 14
          check-latest: true

      - name: Setup yarn
        run: npm i -g yarn

      - name: Cache Nuxt
        id: nuxt-cache-build
        uses: actions/cache@v2.1.0
        with:
          path: |
            .nuxt
            node_modules
          key: ${{ runner.os }}-nuxt-logotip4ik-portfolio-v4-build-${{ hashFiles(format('{0}{1}', github.workspace, '/package-lock.json')) }}

      - name: Install dependencies
        if: steps.nuxt-cache-build.outputs.cache-hit != 'true'
        run: yarn install

      - name: Building
        id: build
        run: yarn build

      - name: Send message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ${{ github.actor }} created commit:
            Commit message: ${{ github.event.commits[0].message }}

            Repository: ${{ github.repository }}

            See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}

            ✅ Build stage was successful
