name: ci

on:
  push:
    branches:
      - v4-pika

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 14
          check-latest: true

      - name: Setup yarn
        run: npm i -g yarn

      - name: Cache Nuxt
        id: nuxt-cache-build
        uses: actions/cache@v3
        with:
          path: |
            .nuxt
            node_modules
          key: ${{ runner.os }}-nuxt-logotip4ik-portfolio-v4-build-${{ hashFiles(format('{0}{1}', github.workspace, '/yarn.lock')) }}

      - name: Install dependencies
        if: steps.nuxt-cache-build.outputs.cache-hit != 'true'
        run: yarn install --non-interactive --force

      - name: Building
        id: build
        run: yarn build

      - name: Hide log
        run: |
          echo "::add-mask::${{secrets.napkinAccountApiKey}}"

      - name: Send message
        run: |
          curl --request POST \
            --url https://logotype.npkn.net/tg-builds/ \
            --header 'Content-Type: application/json' \
            --header 'napkin-account-api-key: ${{ secrets.napkinAccountApiKey }}' \
            --data '{ "repo": "${{ github.repository }}", "commit": "${{github.sha}}" }'
